### ISSUE TITLE
日志显示record not found

### ISSUE THREAD

**Issue by sssssm-1113** [WayneJz/teslamate-addr-fix#18]
/workspace/go/pkg/mod/gorm.io/gorm@v1.24.1-0.20221019064659-5dd2bb482755/callbacks.go:134 record not found
[1.566ms] [rows:0] SELECT * FROM "positions" WHERE id = 0 ORDER BY "positions"."id" LIMIT 1

**Comment by sssssm-1113** [comment]
[error] failed to initialize database, got error failed to connect to `host=database user=teslamate database=teslamate`: hostname resolving error

**Comment by WayneJz** [comment]
数据库 host 名称写错了，应该是 ip 地址或者域名，不是 database

**Comment by sssssm-1113** [comment]
teslamate-addr-fix-1  | 2024/06/11 12:01:52 /workspace/go/pkg/mod/gorm.io/gorm@v1.24.1-0.20221019064659-5dd2bb482755/gorm.go:206
teslamate-addr-fix-1  | [error] failed to initialize database, got error failed to connect to `host=10.0.0.245 user=teslamate database=teslamate`: dial error (dial tcp 10.0.0.245:5432: connect: connection refused)
teslamate-addr-fix-1  | panic: failed to connect to `host=10.0.0.245 user=teslamate database=teslamate`: dial error (dial tcp 10.0.0.245:5432: connect: connection refused)
teslamate-addr-fix-1  | 
teslamate-addr-fix-1  | goroutine 1 [running]:
teslamate-addr-fix-1  | main.main()
teslamate-addr-fix-1  |         /workspace/teslamate-addr-fix/main.go:66 +0x266
teslamate-addr-fix-1 exited with code 2
修改了之后仍然有报错。
